/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


//  !!!I gave the necessary general info for this part in part_b_client.c file with info on author.!!!

/*
This code is for server part of part_b. It receives the message from a client and executes blackbox function on it. 

*/

#include "part_b.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <string.h>
#include <fcntl.h>
#include <sys/wait.h>



/*
Below function takes argp as parameter which has data sent from client as fields and executes blackbox with argp->path path.
*/

char **
execute_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static char * result; //result to be returned to client

    pid_t pid;
    int c2p[2], p2c[2], fd_out; //pipes for communication with child process and parent process and fd_out is file descriptor for
                                //output file
    int PARENT_READ = 0;  // read end for pipe c2p
    int CHILD_WRITE = 1; // write end for c2p
    int CHILD_READ = 0; ; //read end for p2c
    int PARENT_WRITE = 1  //write end for p2c
    char buffer[1000000]; //buffer for return value of blackbox
    
 //below I open pipes for communication with child process
    if( (pipe(c2p) == -1) || (pipe(p2c) == -1)) {
        perror("FAIL:\nFailed to setup pipeline\n");
    }

//below I do forking
    if((pid = fork()) == -1){
        perror("FAIL:\nFailed to fork.\n");
    }
    
 // below from 57 to 65 is for child process
    if(pid == 0){
// below first I connect stdout and stderr of child to c2p pipe. Also I connect stdin of child to p2c pipe. Then I close the
    //unused pipe ends. Then I execute blackbox.
    if((dup2(c2p[CHILD_WRITE], STDOUT_FILENO) == -1) || (dup2(c2p[CHILD_WRITE],STDERR_FILENO) == -1)|| (dup2(p2c[CHILD_READ], STDIN_FILENO) == -1)){
        perror("FAIL:\nFailed to redirect console input.\n");
    }else if((close(c2p[PARENT_READ]) == -1) || (close(c2p[CHILD_WRITE]) == -1) || (close(p2c[PARENT_WRITE]) == -1)){
        perror("FAIL:\nFailed to close unused pipe descriptors.\n");
    }
        execl(argp->path, argp->path, NULL);
        perror("FAIL:\nFailed to execute blackbox.\n");
    }
    

 // below is code for parent process. First I close unused pipe end below.
    if((close(c2p[CHILD_WRITE]) == -1) || (close(p2c[CHILD_READ]) == -1) ){
        perror("FAIL:\nFailed to close unused pipe descriptors.\n");
    }

	char varA[1000]; // is data for giving to child process
	sprintf(varA, "%d %d\n" , argp->a, argp->b);
   
//below, varA is written to pipe for child to read.
    if((write(p2c[PARENT_WRITE], varA, strlen(varA)+1)) == -1){
        perror("FAIL:\nFailed to redirect stdin to blackbox.");
    }

   //below, I close write end for p2c to send signal of write.
    if((close(p2c[PARENT_WRITE]) == -1)){
        perror("FAIL:\nFailed to close unused pipe descriptors.\n");
    }

// below I wait for the child to finish execution
    wait(NULL);

    // below I read and pare the output of child process (blackbox). len is the byte length of message received from it.
    // I append the termination character for a string at the end of buffer (buffer is the message read from the pipe coming from
    // child). 
    int len = read(c2p[PARENT_READ], buffer, sizeof(buffer));
	if(len == -1){
		perror("FAIL:\nFailed to read output for blackbox.\n");
	}
    buffer[len] = '\0';
    result=buffer;


  // below I return the result of child process.
	return &result;
}