/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	char path[256];
	int a;
	int b;
};
typedef struct inputs inputs;

#define PARTB 0x12345678
#define PARTB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define execute 1
extern  char ** execute_1(inputs *, CLIENT *);
extern  char ** execute_1_svc(inputs *, struct svc_req *);
extern int partb_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define execute 1
extern  char ** execute_1();
extern  char ** execute_1_svc();
extern int partb_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
